insert into public.sources (
  source_key,
  name,
  provider,
  geography,
  category,
  source_type,
  integration_status,
  reliability_level,
  used_in_current_prototype,
  planned_for_pilot,
  decision_grade,
  license_note,
  access_note,
  usage_in_geoai,
  limitations,
  recommended_next_step
) values
  (
    'synthetic-demo-layers',
    'Synthetic Demo Layers',
    'GeoAI demo dataset',
    'Dubai, UAE',
    'demo_geospatial',
    'mock',
    'mock',
    'demo',
    true,
    true,
    false,
    'Synthetic demo data for product demonstration only.',
    'Bundled locally with the MVP.',
    'Map visualization, selection, evidence context, and mock scoring.',
    'Not official parcels, zoning, infrastructure, utilities, or risk boundaries.',
    'Replace or validate with official/customer GIS layers before pilot decisions.'
  ),
  (
    'demo-market-context-seed-static',
    'Demo Market Context / seed_static',
    'GeoAI demo market model',
    'Dubai, UAE',
    'market_context',
    'mock',
    'mock',
    'demo',
    true,
    true,
    false,
    'Synthetic normalized indices only.',
    'Bundled locally with the MVP.',
    'Area matching, market context notes, and demo-normalized score interpretation.',
    'Does not contain official transaction prices, rents, absorption, ownership, or valuation data.',
    'Connect official or licensed market feeds and document assumptions.'
  ),
  (
    'dubai-land-department',
    'Dubai Land Department Real Estate Data',
    'Dubai Land Department',
    'Dubai, UAE',
    'real_estate',
    'official',
    'planned',
    'high',
    false,
    true,
    true,
    'Official access and licensing terms must be validated.',
    'Planned adapter; credentials/access not connected in v0.1.',
    'Future transaction, registration, and market validation source.',
    'Not connected; GeoAI must not claim official DLD values until adapter validation is complete.',
    'Confirm access route, fields, licensing, and pilot data scope.'
  ),
  (
    'dubai-pulse-dld-apis',
    'Dubai Pulse DLD APIs',
    'Dubai Pulse / Data Dubai',
    'Dubai, UAE',
    'open_data',
    'open_data',
    'planned',
    'medium',
    false,
    true,
    false,
    'Open data terms vary by dataset and must be reviewed.',
    'Planned adapter; no live API calls in v0.1.',
    'Future public dataset enrichment and validation.',
    'Availability, fields, rate limits, and freshness are not validated yet.',
    'Prototype a read-only adapter and source metadata audit.'
  ),
  (
    'dubai-municipality-gis-geodubai',
    'Dubai Municipality GIS / GeoDubai',
    'Dubai Municipality / GeoDubai',
    'Dubai, UAE',
    'planning_gis',
    'official',
    'planned',
    'high',
    false,
    true,
    true,
    'Official GIS access, terms, and sharing constraints must be validated.',
    'Planned adapter; not connected in v0.1.',
    'Future planning, parcel, zoning, right-of-way, and urban context evidence.',
    'Not connected; no official planning or parcel claims are made.',
    'Define pilot layers, permissions, and RLS-safe storage model.'
  ),
  (
    'dubai-2040-urban-master-plan',
    'Dubai 2040 Urban Master Plan',
    'Government of Dubai',
    'Dubai, UAE',
    'planning_strategy',
    'official',
    'planned',
    'medium',
    false,
    true,
    false,
    'Public plan material must be cited and interpreted conservatively.',
    'Planned evidence source; no live ingestion in v0.1.',
    'Strategic planning context and narrative guardrails.',
    'Plan interpretation does not equal parcel-level approval, zoning, or entitlement.',
    'Create citation-backed planning context cards.'
  ),
  (
    'osm-geofabrik',
    'OpenStreetMap / Geofabrik',
    'OpenStreetMap contributors / Geofabrik',
    'Dubai, UAE',
    'infrastructure',
    'open_data',
    'planned',
    'medium',
    false,
    true,
    false,
    'ODbL licensing and attribution requirements apply.',
    'Planned adapter; no external download in v0.1.',
    'Future roads, POIs, transit context, and accessibility indicators.',
    'Crowdsourced coverage and attribution requirements must be handled carefully.',
    'Add attribution-aware extract workflow and freshness metadata.'
  ),
  (
    'copernicus-sentinel-landsat',
    'Copernicus Sentinel / USGS Landsat',
    'ESA Copernicus / USGS',
    'Dubai, UAE',
    'remote_sensing',
    'open_data',
    'planned',
    'medium',
    false,
    true,
    false,
    'Open satellite data terms and attribution apply.',
    'Planned adapter; no imagery ingestion in v0.1.',
    'Future heat, vegetation, land-cover, and change-detection evidence.',
    'Resolution and revisit cadence may not support parcel-grade conclusions.',
    'Prototype index computation and cloud/temporal quality metadata.'
  ),
  (
    'commercial-vhr-imagery',
    'Commercial Very High Resolution Imagery',
    'Commercial imagery provider placeholder',
    'Dubai, UAE',
    'remote_sensing',
    'commercial',
    'planned',
    'high',
    false,
    true,
    true,
    'Commercial license required before use or redistribution.',
    'Placeholder only; no vendor connected in v0.1.',
    'Future construction monitoring, site verification, and report imagery.',
    'Cannot be used until licensed and provenance is documented.',
    'Select provider, validate rights, and define storage/security rules.'
  ),
  (
    'customer-uploaded-documents',
    'Customer-uploaded CSV / GeoJSON / Documents',
    'Customer provided',
    'Project-specific',
    'documents',
    'customer',
    'planned',
    'medium',
    false,
    true,
    false,
    'Customer data is governed by customer agreement and project controls.',
    'Upload workflow planned; no database storage in v0.1.',
    'Future customer evidence, site boundaries, memos, and due diligence materials.',
    'Requires auth, tenant isolation, retention policy, and audit trail.',
    'Implement secure upload, parsing, validation, and RLS before pilots.'
  )
on conflict (source_key) do update set
  name = excluded.name,
  provider = excluded.provider,
  geography = excluded.geography,
  category = excluded.category,
  source_type = excluded.source_type,
  integration_status = excluded.integration_status,
  reliability_level = excluded.reliability_level,
  used_in_current_prototype = excluded.used_in_current_prototype,
  planned_for_pilot = excluded.planned_for_pilot,
  decision_grade = excluded.decision_grade,
  license_note = excluded.license_note,
  access_note = excluded.access_note,
  usage_in_geoai = excluded.usage_in_geoai,
  limitations = excluded.limitations,
  recommended_next_step = excluded.recommended_next_step,
  updated_at = now();

insert into public.spatial_layers (source_id, layer_key, name, geometry_type, status, metadata)
select id, 'demo-dubai-spatial-layers', 'Demo Dubai Spatial Layers', 'Mixed', 'mock', '{"mode":"seed_geojson","note":"Synthetic MVP geometries only"}'::jsonb
from public.sources
where source_key = 'synthetic-demo-layers'
on conflict (layer_key) do update set
  name = excluded.name,
  geometry_type = excluded.geometry_type,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();
