import fs from "node:fs/promises";
import path from "node:path";
import AxeBuilder from "@axe-core/playwright";
import { expect,test,type Browser,type Page } from "@playwright/test";
import { ROLE_OPTIONS,SCENARIO_OPTIONS,SCREENING_CAVEAT } from "../../src/pilots/rosimushchestvo/data/implementation-baseline";

const route="/pilots/rosimushchestvo",evidence=path.join(process.cwd(),"artifacts","pilot-rf-002","screenshots"),projectKey="geoai:pilot-rf-002:project:v1";
const role="Руководитель портфеля",scenario="S2 — Вовлечение в оборот",preset="S2 · Вовлечение в оборот";
async function stable(page:Page){await page.evaluate(()=>document.fonts.ready);await expect(page.getByTestId("rosim-pilot-root")).toBeVisible()}
async function roleList(page:Page){await page.locator('[data-testid="role-switcher"] > button').click();return page.getByRole("listbox",{name:"2 Роль · 11 ролей"})}
async function scenarioList(page:Page){await page.locator('[data-testid="scenario-selector"] > button').click();return page.getByRole("listbox",{name:"3 Сценарий · 8 P0-сценариев"})}
async function noOverflow(page:Page,label:string){const result=await page.evaluate(()=>({document:document.documentElement.scrollWidth-document.documentElement.clientWidth,offenders:[...document.querySelectorAll<HTMLElement>("body *")].filter(e=>!e.closest('[data-testid="pilot-map"]')).filter(e=>{const s=getComputedStyle(e);return e.clientWidth>0&&e.scrollWidth-e.clientWidth>1&&!(["visible","clip"].includes(s.overflowX))}).slice(0,10).map(e=>({tag:e.tagName,class:e.className,text:e.innerText?.slice(0,60),client:e.clientWidth,scroll:e.scrollWidth}))}));expect(result.document,`${label}: document overflow`).toBeLessThanOrEqual(0);expect(result.offenders,`${label}: clipped runtime content`).toEqual([])}
async function axe(page:Page,label:string){const r=await new AxeBuilder({page}).include('[data-testid="rosim-pilot-root"]').withTags(["wcag2a","wcag2aa","wcag21a","wcag21aa","wcag22aa"]).analyze();expect(r.violations.filter(v=>v.impact==="serious"||v.impact==="critical"),`${label}: Axe`).toEqual([])}
test.describe.configure({mode:"serial"});

test("@p0 exact taxonomy, defaults, Escape, focus and behavior",async({page})=>{await page.goto(`${route}?view=workspace`);await stable(page);await expect(page).toHaveTitle("GeoAI — Федеральное имущество");await expect(page.getByTestId("persistent-disclaimer")).toContainText(SCREENING_CAVEAT);await expect(page.getByTestId("fixture-contract")).toHaveText("2400/320/8/41");const rl=await roleList(page);await expect(rl.getByRole("option")).toHaveText([...ROLE_OPTIONS]);await page.keyboard.press("Escape");await expect(rl).toHaveCount(0);await expect(page.locator('[data-testid="role-switcher"] > button')).toBeFocused();const r2=await roleList(page);await r2.getByRole("option",{name:"Инспектор / мониторинг",exact:true}).click();await expect(page.getByTestId("scenario-selector")).toContainText("S6 — Неиспользование / ненадлежащее использование");await page.getByText("Как роль и сценарий изменяют представление").click();await expect(page.getByText(/Проверяемый сигнал, не вывод о нарушении/)).toBeVisible();const r3=await roleList(page);await r3.getByRole("option",{name:role,exact:true}).click();const sl=await scenarioList(page);await expect(sl.getByRole("option")).toHaveText(SCENARIO_OPTIONS.map(s=>s.label));await sl.getByRole("option",{name:"S3 — Аренда / торги / приватизация",exact:true}).click();await expect(page.getByTestId("layer-preset")).toHaveText("S3 · Аренда / торги / приватизация");const s2=await scenarioList(page);await s2.getByRole("option",{name:scenario,exact:true}).click();await expect(page.getByTestId("layer-preset")).toHaveText(preset);await expect(page.getByText("Демонстрационный вид роли; не является контуром разграничения доступа",{exact:true})).toBeVisible();await page.keyboard.press("Tab");await expect(page.locator(":focus")).toBeVisible()});

test("@p0 golden path, comparison, evidence, saved state, report Back and Print",async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,"print",{configurable:true,value:()=>sessionStorage.setItem("print-called","yes")}));await page.goto(`${route}?view=workspace`);await page.evaluate(k=>localStorage.removeItem(k),projectKey);await page.getByRole("button",{name:/Найти объекты/}).click();await expect(page.getByTestId("results-screen")).toBeVisible();await expect(page.getByTestId("runtime-context-receipt")).toContainText(role);await expect(page.getByTestId("runtime-context-receipt")).toContainText(scenario);await expect(page.getByTestId("interpreted-query")).toContainText("Конфликт: да");await expect(page.getByTestId("interpreted-query")).toContainText("Неподдерживаемые условия: нет");await page.getByRole("button",{name:"Выбрать ДЕМО-RF-MOW-207"}).click();await page.getByRole("button",{name:"Выбрать ДЕМО-RF-MOW-288"}).click();await expect(page.getByRole("button",{name:/Сравнить 4 объекта/})).toBeEnabled();await page.getByRole("button",{name:"Снять выбор ДЕМО-RF-MOW-114"}).click();await page.getByRole("button",{name:/Сравнить 3 объекта/}).click();await expect(page.getByTestId("comparison-card")).toHaveCount(3);await page.getByTestId("comparison-card").first().getByRole("button",{name:"Открыть объект"}).click();await expect(page.getByTestId("object-dashboard")).toContainText("ДЕМО-RF-MOW-031");await expect(page.getByTestId("object-dashboard")).toContainText(role);await page.getByRole("button",{name:"Сведения об источниках"}).click();await expect(page.locator('[data-testid="evidence-screen"] [data-source-id]')).toHaveCount(4);await expect(page.getByTestId("evidence-screen")).toContainText("Нет данных ≠ ноль");await page.getByRole("button",{name:"Закрыть сведения"}).click();await page.getByRole("button",{name:"Добавить в проект"}).click();await expect(page.getByTestId("saved-state-receipt")).toContainText(role);await expect(page.getByTestId("saved-state-receipt")).toContainText(scenario);await expect(page.getByTestId("saved-state-receipt")).toContainText(preset);await page.reload();await expect(page.getByTestId("saved-state-receipt")).toContainText("ДЕМО-RF-MOW-031");await page.getByRole("button",{name:"Открыть проект"}).click();await expect(page.getByTestId("results-screen")).toBeVisible();await page.getByRole("button",{name:"ДЕМО-RF-MOW-031",exact:true}).click();await page.getByRole("button",{name:"Открыть отчёт"}).click();await expect(page.getByTestId("printable-report")).toContainText(role);await expect(page.getByTestId("printable-report")).toContainText(scenario);await expect(page.getByTestId("printable-report")).toContainText(SCREENING_CAVEAT);await page.getByRole("button",{name:"Печать"}).click();await expect.poll(()=>page.evaluate(()=>sessionStorage.getItem("print-called"))).toBe("yes");await page.getByRole("button",{name:"Назад"}).click();await expect(page.getByTestId("object-dashboard")).toBeVisible()});

test("@p0 approved runtime states and map fallback",async({page})=>{for(const state of ["loading","empty","map-error","source-unavailable","permission-required"]){await page.goto(`${route}?view=state&state=${state}`);await expect(page.getByTestId(`state-${state}`)).toBeVisible();await expect(page.getByTestId(`state-${state}`)).toContainText(SCREENING_CAVEAT);await expect(page.getByTestId(`state-${state}`)).toContainText("Конфликт: да");await expect(page.getByTestId(`state-${state}`)).toContainText("Неподдерживаемые условия: нет")}await page.goto(`${route}?view=state&state=map-error`);await expect(page.getByText("ДЕМО-RF-MOW-031 · реестровый конфликт",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Открыть список"}).click();await expect(page.getByTestId("results-screen")).toBeVisible();await page.goto(`${route}?view=object&object=ДЕМО-RF-MOW-031`);await page.getByRole("button",{name:"Открыть границу доступа"}).click();await expect(page.getByTestId("state-permission-required")).toBeVisible()});

test("@p0 all roles and scenarios alter visible manifest",async({page})=>{await page.goto(`${route}?view=workspace`);await page.getByText("Как роль и сценарий изменяют представление").click();for(const r of ROLE_OPTIONS){const list=await roleList(page);await list.getByRole("option",{name:r,exact:true}).click();await expect(page.getByTestId("role-switcher")).toContainText(r);await expect(page.getByTestId("fixture-contract")).toHaveText("2400/320/8/41")}for(const s of SCENARIO_OPTIONS){const list=await scenarioList(page);await list.getByRole("option",{name:s.label,exact:true}).click();await expect(page.getByTestId("layer-preset")).toHaveText(s.preset);await expect(page.locator("details")).toContainText(s.output);await expect(page.locator("details")).toContainText(s.caveat);await expect(page.locator("details")).toContainText(s.nextAction)}});

test("@p0 runtime data-honesty gate",async({page})=>{for(const view of ["workspace","results","comparison","object","evidence","projects","report"]){const object=["object","evidence","report"].includes(view)?"&object=ДЕМО-RF-MOW-031":"";await page.goto(`${route}?view=${view}${object}`);const body=await page.locator("body").innerText();expect(body).not.toMatch(/official cadastral validation|confirmed ownership|certified valuation|approved site|guaranteed best use|production-ready|pilot-ready/i);expect(body).not.toContain("Руководитель / центральный аппарат");expect(body).not.toContain("Вовлечение неиспользуемых объектов");expect(body).not.toContain("Prototype v1")}await page.goto(`${route}?view=evidence&object=ДЕМО-RF-MOW-031`);await expect(page.locator("body")).toContainText("Публичный контекст");await expect(page.locator("body")).toContainText("Требуется разрешение");await expect(page.locator("body")).toContainText("Синтетическая гипотеза")});

async function capture(browser:Browser,input:{name:string;width:number;height:number;url:string;testId:string;full?:boolean}){const context=await browser.newContext({viewport:{width:input.width,height:input.height},colorScheme:"light",reducedMotion:"reduce"});const page=await context.newPage(),errors:string[]=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});await page.goto(input.url);await stable(page);await expect(page.getByTestId(input.testId)).toBeVisible();await noOverflow(page,input.name);await axe(page,input.name);expect(errors,`${input.name}: console errors`).toEqual([]);await page.screenshot({path:path.join(evidence,`${input.name}.png`),animations:"disabled",fullPage:input.full});await context.close()}
test("@p0 six viewport Playwright/Axe/screenshot matrix",async({browser})=>{await fs.mkdir(evidence,{recursive:true});for(const x of [{name:"workspace-1440x900",width:1440,height:900,url:`${route}?view=workspace`,testId:"workspace-screen"},{name:"results-1280x800",width:1280,height:800,url:`${route}?view=results`,testId:"results-screen"},{name:"workspace-1024x768",width:1024,height:768,url:`${route}?view=workspace`,testId:"workspace-screen"},{name:"results-768x1024",width:768,height:1024,url:`${route}?view=results`,testId:"results-screen"},{name:"workspace-393x852",width:393,height:852,url:`${route}?view=workspace`,testId:"workspace-screen"},{name:"results-430x932",width:430,height:932,url:`${route}?view=results`,testId:"results-screen"}])await capture(browser,x)});
test("@p0 decision screen Playwright/Axe/screenshot matrix",async({browser})=>{await fs.mkdir(evidence,{recursive:true});const selected="&role=Руководитель%20портфеля&scenario=S2";for(const x of [{name:"comparison-desktop-1440x900",width:1440,height:900,url:`${route}?view=comparison&compare=4${selected}`,testId:"comparison-screen"},{name:"comparison-mobile-393x852",width:393,height:852,url:`${route}?view=comparison&compare=4${selected}`,testId:"comparison-screen"},{name:"object-dashboard-desktop-1440x900",width:1440,height:900,url:`${route}?view=object&object=ДЕМО-RF-MOW-031${selected}`,testId:"object-dashboard"},{name:"object-dashboard-mobile-430x932",width:430,height:932,url:`${route}?view=object&object=ДЕМО-RF-MOW-031${selected}`,testId:"object-dashboard"},{name:"evidence-768x1024",width:768,height:1024,url:`${route}?view=evidence&object=ДЕМО-RF-MOW-031${selected}`,testId:"evidence-screen"},{name:"projects-1280x800",width:1280,height:800,url:`${route}?view=projects${selected}`,testId:"projects-screen"},{name:"printable-report",width:794,height:1123,url:`${route}?view=report&object=ДЕМО-RF-MOW-031${selected}`,testId:"printable-report",full:true}])await capture(browser,x)});
