import { ReportPrintMap } from "@/components/reports/report-print-map";
import {
  PrintCard,
  PrintList,
  PrintPage,
  PrintSection,
  ReportHeader,
  SourceLineagePrintSection
} from "@/components/reports/report-print-primitives";
import { getDemoNarrativeByProjectKey } from "@/src/data/demo-narratives";
import { getClientPilotPackageForProject } from "@/src/data/pilot-packages";
import { scoreSummaryRows, type AnalysisReportDeliverable } from "@/src/lib/report-deliverables";

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC"
  }).format(new Date(value));
}

function formatCoordinate(point: AnalysisReportDeliverable["coordinates"]) {
  if (!point) return "Coordinates unavailable";
  return `${point.latitude.toFixed(6)}, ${point.longitude.toFixed(6)}`;
}

function formatArea(areaSqM?: number) {
  if (!areaSqM && areaSqM !== 0) return "Not available";
  return areaSqM >= 1_000_000
    ? `${(areaSqM / 1_000_000).toFixed(2)} sq km`
    : `${Math.round(areaSqM).toLocaleString()} sq m`;
}

function formatPerimeter(perimeterM?: number) {
  if (!perimeterM && perimeterM !== 0) return "Not available";
  return perimeterM >= 1_000
    ? `${(perimeterM / 1_000).toFixed(2)} km`
    : `${Math.round(perimeterM).toLocaleString()} m`;
}

export function AnalysisReportPrint({ report }: { report: AnalysisReportDeliverable }) {
  const scoreRows = scoreSummaryRows(report.scoreSummary);
  const spatialContext = report.selectedObject?.spatialContext;
  const demoNarrative = getDemoNarrativeByProjectKey(report.projectKey);
  const clientPilotPackage = getClientPilotPackageForProject(report.projectKey);

  return (
    <article className="geoai-print-report">
      <PrintPage>
        <ReportHeader
          title="GeoAI Analysis Report"
          subtitle={report.subtitle}
          badge="Demo/MVP report"
        />

        <div className="geoai-print-meta-grid">
          <PrintCard label="Selected target" value={report.targetLabel} />
          <PrintCard label="Scenario" value={report.scenario} />
          <PrintCard label="Generated" value={formatDate(report.createdAt)} />
          <PrintCard label="Generated by" value={report.generatedBy} />
          <PrintCard label="Decision posture" value={report.decisionPosture} />
          <PrintCard label="Coordinates" value={formatCoordinate(report.coordinates)} />
        </div>

        <div className="geoai-print-top-grid">
          <PrintSection title="Selected Geometry Map">
            <ReportPrintMap
              title={report.targetLabel}
              subtitle="Selected geometry / map context"
              coordinates={formatCoordinate(report.coordinates)}
              geometryLabel={report.analysisTarget?.geometry?.type ?? spatialContext?.geometryType ?? "Point selection"}
            />
            <p className="geoai-print-note">Selected geometry is user-uploaded/demo/open-data context; official validation required.</p>
          </PrintSection>

          <PrintSection title="Executive Memo">
            <p>{report.executiveMemo}</p>
            <div className="geoai-print-mini-grid">
              <PrintCard label="Confidence" value={report.analysis?.confidenceLevel ?? "medium"} />
              <PrintCard label="Analysis mode" value={report.analysis?.analysisMode === "openai" ? "AI-generated" : "Demo fallback"} />
            </div>
          </PrintSection>
        </div>

        {demoNarrative ? (
          <div className="geoai-print-two-col">
            <PrintSection title="Decision Question">
              <p>{demoNarrative.decisionQuestion}</p>
            </PrintSection>
            <PrintSection title="Pilot Next Action">
              <p>{clientPilotPackage.validationRequirements[0]}</p>
              <p className="geoai-print-note">{demoNarrative.caveat}</p>
            </PrintSection>
          </div>
        ) : null}

      </PrintPage>

      <PrintPage>
        <div className="geoai-print-two-col">
          <PrintSection title="Score Overview">
            <div className="geoai-print-score-grid">
              {scoreRows.map((score) => (
                <PrintCard key={score.label} label={score.label} value={`${score.value}/100`} />
              ))}
            </div>
          </PrintSection>

          <PrintSection title="Market / Spatial Context">
            <div className="geoai-print-mini-grid">
              <PrintCard label="Market basis" value={report.analysis?.marketContext?.areaName ?? "Demo/sample context"} />
              <PrintCard label="Data mode" value={report.analysis?.project?.dataMode?.replace(/_/g, " ") ?? "demo normalized"} />
              <PrintCard label="Object type" value={report.selectedAoi ? "User-drawn polygon AOI" : spatialContext?.subtype ?? report.selectedObject?.type ?? "point / site"} />
              <PrintCard label="Geometry confidence" value={report.selectedAoi?.confidence ?? spatialContext?.confidenceLevel ?? "validation required"} />
            </div>
          </PrintSection>
        </div>

        {report.selectedAoi ? (
          <PrintSection title="User-Drawn AOI Details">
            <div className="geoai-print-mini-grid">
              <PrintCard label="Geometry" value="Polygon" />
              <PrintCard label="Area" value={formatArea(report.selectedAoi.measurements.areaSqM)} />
              <PrintCard label="Perimeter" value={formatPerimeter(report.selectedAoi.measurements.perimeterM)} />
              <PrintCard label="Vertices" value={String(report.selectedAoi.measurements.vertexCount)} />
              <PrintCard label="Source" value="user_drawn_polygon" />
              <PrintCard label="Status" value="official validation required" />
            </div>
            <p className="geoai-print-note">{report.selectedAoi.limitations[0]}</p>
          </PrintSection>
        ) : null}

        <div className="geoai-print-two-col">
          <PrintSection title="Key Findings">
            <PrintList items={report.keyFindings.slice(0, 6)} />
          </PrintSection>

          <PrintSection title="Risk & Constraints">
            <PrintList items={report.risks.slice(0, 6)} />
          </PrintSection>
        </div>

        <div className="geoai-print-two-col">
          <PrintSection title="Opportunities">
            <PrintList items={(report.opportunities.length > 0 ? report.opportunities : report.keyFindings).slice(0, 4)} />
          </PrintSection>

          <PrintSection title="Screening Signals / Source Basis">
            <PrintList
              items={[
                "Screening output uses deterministic scores and structured source readiness.",
                "Market signals require validation against agreed market snapshots or customer-approved data.",
                "Spatial and geometry context is screening-level unless validated by authorized sources.",
                "Report is intended for decision preparation, not final legal or cadastral approval."
              ]}
            />
          </PrintSection>
        </div>
      </PrintPage>

      <PrintPage>
        <SourceLineagePrintSection lineage={report.sourceLineage} />

        <div className="geoai-print-two-col">
          <PrintSection title="Validation Checklist">
            <PrintList items={report.validationChecklist} />
          </PrintSection>

          <PrintSection title="Recommended Next Actions">
            <PrintList items={report.nextActions.slice(0, 6)} ordered />
          </PrintSection>
        </div>

        <PrintSection title="Data Honesty Disclaimer">
          <p>{report.dataHonestyNote}</p>
          {report.limitations.slice(0, 4).map((item, index) => (
            <p key={`analysis-print-limitation-${index}`}>{item}</p>
          ))}
        </PrintSection>
      </PrintPage>
    </article>
  );
}
