import { ReportPrintMap } from "@/components/reports/report-print-map";
import {
  PrintCard,
  PrintList,
  PrintPage,
  PrintSection,
  ReportHeader,
  SourceLineagePrintSection
} from "@/components/reports/report-print-primitives";
import {
  buildComparisonDecisionResult,
  DECISION_RESULT_CAVEAT
} from "@/src/lib/dashboard/dashboard-model";
import type { ComparisonReportDeliverable } from "@/src/lib/report-deliverables";
import type { ScoreKey } from "@/src/types/geo";

const scoreLabels: Record<ScoreKey, string> = {
  developmentPotential: "Development Potential",
  investmentAttractiveness: "Investment Attractiveness",
  accessibility: "Accessibility",
  infrastructureReadiness: "Infrastructure Readiness",
  climateHeatRisk: "Climate / Heat Risk",
  overallRisk: "Overall Risk"
};

const scoreOrder: ScoreKey[] = [
  "developmentPotential",
  "investmentAttractiveness",
  "accessibility",
  "infrastructureReadiness",
  "climateHeatRisk",
  "overallRisk"
];

function formatDate(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Not recorded";
  return new Intl.DateTimeFormat("en", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC"
  }).format(date);
}

function readScore(item: NonNullable<ComparisonReportDeliverable["comparison"]>["items"][number], key: ScoreKey) {
  return item.scores[key];
}

export function ComparisonReportPrint({ report }: { report: ComparisonReportDeliverable }) {
  const comparison = report.comparison;
  const decisionResult = buildComparisonDecisionResult(report);

  return (
    <article className="geoai-print-report" data-decision-contract-version={decisionResult.contractVersion}>
      <PrintPage>
        <ReportHeader
          title="GeoAI Comparison Report"
          subtitle={report.subtitle}
          badge="Decision comparison"
        />

        <div className="geoai-print-meta-grid">
          <PrintCard label="Project / report" value={report.title} />
          <PrintCard label="Scenario" value={decisionResult.scenario.label} field="scenario" />
          <PrintCard label="Result generated" value={formatDate(decisionResult.generatedAt)} field="generated-at" />
          <PrintCard label="Compared items" value={report.comparedItems.length} />
          <PrintCard label="Leading screening option" value={decisionResult.target.label} field="target" />
          <PrintCard label="Coordinates" value={decisionResult.coordinates?.label ?? "Coordinates unavailable"} field="coordinates" />
          <PrintCard label="Primary score" value={decisionResult.primaryScore !== null ? `${decisionResult.primaryScore}/100` : "Not available"} field="suitability" />
          <PrintCard label="Confidence" value={decisionResult.confidence.label} field="confidence" />
          <PrintCard label="Validation" value={decisionResult.validation.status} field="validation" />
          <PrintCard label="Generated by" value="GeoAI" />
        </div>

        <div className="geoai-print-top-grid">
          <PrintSection title="Comparison Map">
            <ReportPrintMap
              title="Illustrative comparison context"
              subtitle="Illustrative selected sites / assets"
              comparison={report}
              geometryLabel="Illustrative print-safe selected-site context; official validation required"
            />
          </PrintSection>

          <PrintSection title="Decision Posture">
            <p data-report-field="decision-posture"><strong>{decisionResult.decision.posture}</strong></p>
            <p data-report-field="rationale">{decisionResult.decision.rationale}</p>
            {decisionResult.decision.detail !== decisionResult.decision.rationale ? <p>{decisionResult.decision.detail}</p> : null}
          </PrintSection>
        </div>

        <div className="geoai-print-two-col">
          <PrintSection title="Decision Question">
            <p data-report-field="decision-question">{decisionResult.decisionQuestion}</p>
          </PrintSection>
          <PrintSection title="Validation Next Action">
            <p data-report-field="next-action">{decisionResult.nextAction.detail}</p>
            <p className="geoai-print-note">{decisionResult.caveat}</p>
          </PrintSection>
        </div>

        <PrintSection title="Summary Cards">
          <div className="geoai-print-score-grid">
            {report.comparedItems.map((item, index) => (
              <PrintCard
                key={`${item.name}-${index}`}
                label={`${index + 1}. ${item.name}`}
                value={item.overallScore !== null ? `${item.overallScore}/100` : "Validation required"}
                note={`${item.riskLevel} / ${item.recommendedUse}`}
              />
            ))}
          </div>
        </PrintSection>
      </PrintPage>

      <PrintPage>
        <PrintSection title="Score Comparison">
          {comparison ? (
            <div className="geoai-print-table-wrap">
              <table className="geoai-print-table">
                <thead>
                  <tr>
                    <th>Metric</th>
                    {comparison.items.map((item, index) => (
                      <th key={`${item.item.id}-${index}`}>{item.item.name}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {scoreOrder.map((scoreKey) => (
                    <tr key={scoreKey}>
                      <td>{scoreLabels[scoreKey]}</td>
                      {comparison.items.map((item, index) => (
                        <td key={`${scoreKey}-${item.item.id}-${index}`}>{readScore(item, scoreKey)}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="geoai-print-score-grid">
              {report.comparedItems.map((item, index) => (
                <PrintCard key={`fallback-score-${index}`} label={item.name} value={item.overallScore ?? "N/A"} note={item.keyConcern} />
              ))}
            </div>
          )}
        </PrintSection>

        <div className="geoai-print-two-col">
          <PrintSection title="Differentiated Risks">
            <PrintList items={decisionResult.risks.map((item) => item.detail).slice(0, 6)} />
          </PrintSection>

          <PrintSection title="Market / Access / Climate Trade-offs">
            <PrintList
              items={report.comparedItems.map((item) => `${item.name}: ${item.keyConcern}`).slice(0, 6)}
            />
          </PrintSection>
        </div>

        <PrintSection title="Key Trade-offs">
          <PrintList items={decisionResult.drivers.map((item) => item.detail).slice(0, 6)} />
        </PrintSection>
      </PrintPage>

      <PrintPage>
        <PrintSection title="Evidence / Source Basis">
          <p><strong>{decisionResult.sourceBasis.label}</strong></p>
          <PrintList items={[...decisionResult.sourceBasis.items]} />
        </PrintSection>

        <SourceLineagePrintSection lineage={report.sourceLineage} />

        <div className="geoai-print-two-col">
          <PrintSection title="Validation Checklist">
            <PrintList items={decisionResult.validation.gaps.map((item) => item.detail)} />
          </PrintSection>

          <PrintSection title="Recommended Next Actions">
            <PrintList items={[decisionResult.nextAction.detail]} ordered />
          </PrintSection>
        </div>

        <PrintSection title="Data Honesty Disclaimer">
          <p data-report-field="caveat">{DECISION_RESULT_CAVEAT}</p>
          <p>Engineering and insurance-grade assessment, where relevant, remains outside this screening result.</p>
        </PrintSection>
      </PrintPage>
    </article>
  );
}
