import { ReportPrintMap } from "@/components/reports/report-print-map";
import {
  PrintCard,
  PrintList,
  PrintPage,
  PrintSection,
  ReportHeader,
  SourceLineagePrintSection
} from "@/components/reports/report-print-primitives";
import { getDemoNarrativeByProjectKey } from "@/src/data/demo-narratives";
import { getClientPilotPackageForProject } from "@/src/data/pilot-packages";
import type { ComparisonReportDeliverable } from "@/src/lib/report-deliverables";
import type { ScoreKey } from "@/src/types/geo";

const scoreLabels: Record<ScoreKey, string> = {
  developmentPotential: "Development Potential",
  investmentAttractiveness: "Investment Attractiveness",
  accessibility: "Accessibility",
  infrastructureReadiness: "Infrastructure Readiness",
  climateHeatRisk: "Climate / Heat Risk",
  overallRisk: "Overall Risk"
};

const scoreOrder: ScoreKey[] = [
  "developmentPotential",
  "investmentAttractiveness",
  "accessibility",
  "infrastructureReadiness",
  "climateHeatRisk",
  "overallRisk"
];

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC"
  }).format(new Date(value));
}

function formatPoint(point: ComparisonReportDeliverable["comparedItems"][number]["coordinates"]) {
  if (!point) return "Coordinates unavailable";
  return `${point.latitude.toFixed(5)}, ${point.longitude.toFixed(5)}`;
}

function readScore(item: NonNullable<ComparisonReportDeliverable["comparison"]>["items"][number], key: ScoreKey) {
  return item.scores[key];
}

export function ComparisonReportPrint({ report }: { report: ComparisonReportDeliverable }) {
  const comparison = report.comparison;
  const demoNarrative = getDemoNarrativeByProjectKey(report.projectKey);
  const clientPilotPackage = getClientPilotPackageForProject(report.projectKey);

  return (
    <article className="geoai-print-report">
      <PrintPage>
        <ReportHeader
          title="GeoAI Comparison Report"
          subtitle={report.subtitle}
          badge="Demo comparison"
        />

        <div className="geoai-print-meta-grid">
          <PrintCard label="Project / report" value={report.title} />
          <PrintCard label="Scenario" value={report.scenario} />
          <PrintCard label="Generated" value={formatDate(report.createdAt)} />
          <PrintCard label="Compared items" value={report.comparedItems.length} />
          <PrintCard label="Recommended option" value={report.winnerLabel} />
          <PrintCard label="Generated by" value={report.generatedBy} />
        </div>

        <div className="geoai-print-top-grid">
          <PrintSection title="Comparison Map">
            <ReportPrintMap
              title="Comparison context"
              subtitle="Selected sites / assets"
              comparison={report}
              geometryLabel="Print-safe selected-site context; official validation required"
            />
          </PrintSection>

          <PrintSection title="Winner / Recommendation">
            <p><strong>{report.winnerLabel}</strong></p>
            <p>{comparison?.whyPreferred ?? report.decisionPosture}</p>
            <p>{report.alternativeInterpretation}</p>
          </PrintSection>
        </div>

        {demoNarrative ? (
          <div className="geoai-print-two-col">
            <PrintSection title="Decision Question">
              <p>{demoNarrative.decisionQuestion}</p>
            </PrintSection>
            <PrintSection title="Pilot Next Action">
              <p>{clientPilotPackage.validationRequirements[0]}</p>
              <p className="geoai-print-note">{demoNarrative.caveat}</p>
            </PrintSection>
          </div>
        ) : null}

        <PrintSection title="Summary Cards">
          <div className="geoai-print-score-grid">
            {report.comparedItems.map((item, index) => (
              <PrintCard
                key={`${item.name}-${index}`}
                label={`${index + 1}. ${item.name}`}
                value={item.overallScore !== null ? `${item.overallScore}/100` : "Validation required"}
                note={`${item.riskLevel} / ${item.recommendedUse}`}
              />
            ))}
          </div>
        </PrintSection>
      </PrintPage>

      <PrintPage>
        <PrintSection title="Score Comparison">
          {comparison ? (
            <div className="geoai-print-table-wrap">
              <table className="geoai-print-table">
                <thead>
                  <tr>
                    <th>Metric</th>
                    {comparison.items.map((item, index) => (
                      <th key={`${item.item.id}-${index}`}>{item.item.name}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {scoreOrder.map((scoreKey) => (
                    <tr key={scoreKey}>
                      <td>{scoreLabels[scoreKey]}</td>
                      {comparison.items.map((item, index) => (
                        <td key={`${scoreKey}-${item.item.id}-${index}`}>{readScore(item, scoreKey)}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="geoai-print-score-grid">
              {report.comparedItems.map((item, index) => (
                <PrintCard key={`fallback-score-${index}`} label={item.name} value={item.overallScore ?? "N/A"} note={item.keyConcern} />
              ))}
            </div>
          )}
        </PrintSection>

        <div className="geoai-print-two-col">
          <PrintSection title="Differentiated Risks">
            <PrintList items={report.differentiatedRisks.slice(0, 6)} />
          </PrintSection>

          <PrintSection title="Market / Access / Climate Trade-offs">
            <PrintList
              items={report.comparedItems.map((item) => `${item.name}: ${item.keyConcern}`).slice(0, 6)}
            />
          </PrintSection>
        </div>

        <PrintSection title="Key Trade-offs">
          <PrintList
            items={(report.sharedOpportunities.length > 0
              ? report.sharedOpportunities
              : report.comparedItems.map((item) => `${item.name}: ${item.recommendedUse}`)).slice(0, 6)}
          />
        </PrintSection>
      </PrintPage>

      <PrintPage>
        <SourceLineagePrintSection lineage={report.sourceLineage} />

        <div className="geoai-print-two-col">
          <PrintSection title="Validation Checklist">
            <PrintList items={report.validationChecklist} />
          </PrintSection>

          <PrintSection title="Recommended Next Actions">
            <PrintList items={report.nextActions.slice(0, 6)} ordered />
          </PrintSection>
        </div>

        <PrintSection title="Data Honesty Disclaimer">
          <p>{report.dataHonestyNote}</p>
        </PrintSection>
      </PrintPage>
    </article>
  );
}
