import { CONTEXT_GROUP_LABELS, type PointObjectNormalizedContext } from "@/src/lib/prototype/point-to-object-normalized-context";

export function PointObjectContextDashboard({ context, locale, programme = false }: { context: PointObjectNormalizedContext; locale: "en" | "ru"; programme?: boolean }) {
  const ru = locale === "ru";
  const labels = CONTEXT_GROUP_LABELS[locale];
  const fmt = (value: number) => value.toLocaleString(ru ? "ru-RU" : "en-US");
  const counts = context.metrics.filter(m => m.unit === "count" && m.value !== null && m.value > 0).sort((a,b) => (b.value ?? 0) - (a.value ?? 0));
  const anchor = context.scope.anchor;
  const places = anchor ? context.places.filter(p => p.coordinates && p.distanceM !== null) : [];
  const scope = context.scope.kind === "aoi_interior" ? (ru ? "Внутри выбранной зоны" : "Inside the selected area") : (ru ? `В радиусе ${context.scope.radiusM} м от точки` : `Within ${context.scope.radiusM} m of the point`);
  return <section className="min-w-0 rounded-[20px] border border-line bg-white p-5 sm:p-7" data-testid="normalized-context-dashboard" data-context-scope={context.scope.kind}>
    <h3 className="text-lg font-bold text-[#243447]">{programme ? (ru ? "Контекст программы" : "Programme context") : (ru ? "Инфраструктура и окружение" : "Infrastructure & surroundings")}</h3>
    <p className="mt-1 text-xs leading-5 text-[#52657a]">{scope} · {context.sampleSize === null ? (ru ? "источник недоступен" : "source unavailable") : `${fmt(context.sampleSize)} ${ru ? "возвращённых объектов" : "returned features"}`}{context.capReached ? (ru ? " · достигнут предел выборки" : " · sample cap reached") : ""}.</p>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{context.programmeChecks.map(check => {
      const distance = context.metrics.find(m => m.id === `${check.group}.nearest`)?.value;
      return <article key={check.group} className="min-w-0 rounded-xl border border-[#dce6e3] bg-[#f8fafc] p-3" data-testid={`context-${check.group}`}><p className="text-xs font-bold text-[#52657a]">{labels[check.group]}</p><p className="mt-2 text-xl font-bold tabular-nums text-[#087f8c]">{check.mappedCount === null ? "—" : fmt(check.mappedCount)}</p><p className="mt-1 text-[11px] leading-4 text-[#52657a]">{check.mappedCount === null ? (ru ? "Данные не получены" : "Data not returned") : (ru ? "записей в выборке OSM" : "OSM sample records")}</p>{distance != null ? <p className="mt-2 text-xs text-[#344054]">{fmt(distance)} {ru ? "м по прямой до ближайшего центра" : "m straight-line to nearest centre"}</p> : context.scope.kind === "point_radius" ? <p className="mt-2 text-[11px] text-[#52657a]">{ru ? "Ближайшее расстояние неизвестно" : "Nearest distance unknown"}</p> : null}</article>;
    })}</div>
    {counts.length ? <div className={`mt-5 grid gap-5 ${places.length ? "lg:grid-cols-2" : ""}`}>
      <figure className="min-w-0" data-testid="context-use-chart"><figcaption className="text-sm font-bold text-[#344054]">{ru ? "Состав картированной выборки" : "Mapped sample mix"}</figcaption><div className="mt-3 space-y-2">{counts.slice(0,8).map(m => {
        const share = context.metrics.find(item => item.id === `${m.group}.share`)?.value ?? 0;
        return <div key={m.id}><div className="flex justify-between gap-2 text-xs"><span className="min-w-0 break-words text-[#52657a]">{labels[m.group]}</span><span className="shrink-0 tabular-nums text-[#344054]">{fmt(m.value!)} · {fmt(share)}%</span></div><div className="mt-1 h-2 overflow-hidden rounded bg-[#edf2f4]"><div className="h-full rounded bg-[#087f8c]" style={{width:`${Math.max(0,Math.min(100,share))}%`}} /></div></div>;
      })}</div><p className="mt-3 text-[11px] leading-5 text-[#667085]">{ru ? "Доли записей, не площади, населения или спроса. Ноль в выборке не доказывает отсутствия объекта." : "Shares of records, not area, population or demand. Zero records do not establish absence."}</p></figure>
      {places.length && anchor ? <figure data-testid="context-spatial-plot"><figcaption className="text-sm font-bold text-[#344054]">{ru ? "Возвращённые места вокруг точки" : "Returned places around the point"}</figcaption><svg viewBox="0 0 220 220" className="mt-2 max-h-[260px] w-full rounded-xl bg-[#f4fbfb]" role="img" aria-label={ru ? "Центры объектов в радиусе 400 метров, север сверху" : "Feature centres within 400 metres, north at top"}><circle cx="110" cy="110" r="92" fill="none" stroke="#c8d9d6"/><circle cx="110" cy="110" r="46" fill="none" stroke="#dce6e3"/><path d="M110 14V206M14 110H206" stroke="#dce6e3"/><text x="110" y="11" textAnchor="middle" fontSize="9" fill="#52657a">N</text><circle cx="110" cy="110" r="4" fill="#243447"/>{places.map((p,i) => <g key={p.id}><circle cx={110+(p.coordinates![0]-anchor[0])*111_320*Math.cos(anchor[1]*Math.PI/180)/400*92} cy={110-(p.coordinates![1]-anchor[1])*110_540/400*92} r="8" fill="#087f8c"/><text x={110+(p.coordinates![0]-anchor[0])*111_320*Math.cos(anchor[1]*Math.PI/180)/400*92} y={113-(p.coordinates![1]-anchor[1])*110_540/400*92} textAnchor="middle" fontSize="8" fill="white">{i+1}</text><title>{p.name} · {p.distanceM} m</title></g>)}</svg><ol className="mt-2 grid gap-1 text-[11px] text-[#52657a]">{places.map((p,i) => <li key={p.id}>{i+1}. {p.name} · {fmt(p.distanceM!)} {ru ? "м" : "m"}</li>)}</ol><p className="mt-2 text-[11px] text-[#667085]">{ru ? "Схема центров OSM, не маршруты и не границы учреждений." : "OSM centre diagram, not routes or facility boundaries."}</p></figure> : null}
    </div> : null}
    <div className="mt-5 rounded-xl bg-[#f4fbfb] p-4" data-testid="context-decision-implication"><p className="text-sm leading-6 text-[#344054]">{context.coverage === "unavailable" ? (ru ? "Связи с транспортом, сервисами и общественными пространствами пока оценить нельзя. Обновите источник или подтвердите окружение на месте." : "Transport, service and public-space relationships cannot yet be assessed. Refresh the source or verify the surroundings on site.") : (ru ? `Выборка даёт пространственные ориентиры${counts.length ? `: наиболее представлены ${counts.slice(0,2).map(m => labels[m.group].toLowerCase()).join(" и ")}` : ""}. Для решения проверьте реальные входы, пешеходные связи и действующие услуги.` : `The sample provides spatial reference points${counts.length ? `; ${counts.slice(0,2).map(m => labels[m.group].toLowerCase()).join(" and ")} are most represented` : ""}. Verify actual entrances, pedestrian connections and operating services before deciding.`)}</p>{programme ? <p className="mt-2 text-xs leading-5 text-[#52657a]">{ru ? "Программа — сценарная гипотеза. Школа или клиника на карте не доказывает достаточную мощность: вместимость, доступ и будущую нагрузку нужно подтвердить у оператора. Инвентаризация внутри зоны не заменяет обследование окружения." : "Programme composition is a scenario hypothesis. A mapped school or clinic does not establish sufficient capacity: confirm capacity, access and future load with the operator. Interior inventory does not replace a surrounding catchment assessment."}</p> : null}</div>
    <p className="mt-3 text-[11px] leading-5 text-[#667085]">{context.source.attribution}{context.source.acquiredAt ? ` · ${ru ? "снимок источника" : "source snapshot"} ${new Date(context.source.acquiredAt).toLocaleString(locale)}` : ""} · {ru ? "неполная открытая карта" : "incomplete open map"}.</p>
  </section>;
}
