"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/design-system/button";
import { IdentitySymbol } from "@/components/design-system/identity-symbol";
import { SegmentSwitch } from "@/components/design-system/segment-switch";
import { StatusChip, type StatusChipTone } from "@/components/design-system/status-chip";
import { FEDERAL_DISTRICT_COUNT, FEDERAL_RECORDS, GOLDEN_RECORDS, MOSCOW_RECORDS, SUBJECT_COUNT, getFederalRecord, type FederalRecord } from "../data/federal-fixture";
import { DEFAULT_ROLE, DEFAULT_SCENARIO, ROLE_BEHAVIOR, ROLE_DISCLAIMER, ROLE_OPTIONS, SCENARIO_OPTIONS, SCREENING_CAVEAT, SOURCE_RECEIPTS, type RoleLabel, type ScenarioId } from "../data/implementation-baseline";
import styles from "./implementation-baseline.module.css";

type View="workspace"|"results"|"comparison"|"object"|"evidence"|"projects"|"report"|"state";
type RuntimeState="loading"|"empty"|"map-error"|"source-unavailable"|"permission-required";
type Mode="criteria"|"map";
type SavedProject={title:string;role:RoleLabel;scenario:ScenarioId;selectedIds:string[];activeRecordId:string;query:string;savedAt:string};
const PROJECT_KEY="geoai:pilot-rf-002:project:v1";
const DEFAULT_QUERY="Найти федеральные объекты в Москве для предварительного вовлечения в оборот; показать конфликты реестра, ограничения, спрос и следующий проверяемый шаг";
const DEFAULT_SELECTED=GOLDEN_RECORDS.slice(0,2).map(r=>r.id);
const scenarioById=(id:ScenarioId)=>SCENARIO_OPTIONS.find(s=>s.id===id)??SCENARIO_OPTIONS[1];
const viewFrom=(v:string|null):View=>["workspace","results","comparison","object","evidence","projects","report","state"].includes(v??"")?v as View:"workspace";
const stateFrom=(v:string|null):RuntimeState|null=>["loading","empty","map-error","source-unavailable","permission-required"].includes(v??"")?v as RuntimeState:null;

function Caveat(){return <aside className={styles.caveat} data-testid="persistent-disclaimer"><strong>Демонстрационные данные</strong><p>{SCREENING_CAVEAT}</p></aside>}

function Selector<T extends string>({label,value,options,onChange,testId}:{label:string;value:string;options:readonly {value:T;label:string}[];onChange:(v:T)=>void;testId:string}){
  const [open,setOpen]=useState(false); const trigger=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();setOpen(false);requestAnimationFrame(()=>trigger.current?.focus());}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open]);
  return <div className={styles.selector} data-testid={testId}><button ref={trigger} type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span>{label}</span><strong>{value}</strong><i aria-hidden>⌄</i></button>{open?<div role="listbox" aria-label={label} className={styles.options}>{options.map(o=><button key={o.value} type="button" role="option" aria-selected={o.label===value||o.value===value} onClick={()=>{onChange(o.value);setOpen(false);requestAnimationFrame(()=>trigger.current?.focus())}}>{o.label}</button>)}</div>:null}</div>
}

function TopNav({view,onNavigate}:{view:View;onNavigate:(v:View)=>void}){
  const [menu,setMenu]=useState(false); const trigger=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!menu)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);requestAnimationFrame(()=>trigger.current?.focus())}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[menu]);
  const items:[string,View][]=[["Рабочая область","workspace"],["Результаты","results"],["Проекты","projects"]];
  return <header className={styles.nav}><button className={styles.brand} type="button" onClick={()=>onNavigate("workspace")}><IdentitySymbol/><span><strong>GeoAI</strong><small>Контур федерального имущества</small></span></button><nav aria-label="Основная навигация">{items.map(([l,v])=><button key={v} aria-current={view===v?"page":undefined} onClick={()=>onNavigate(v)}>{l}</button>)}<span>PILOT-RF-002</span><span className={styles.avatar}>РП</span></nav><button ref={trigger} className={styles.menuButton} aria-expanded={menu} aria-label="Открыть навигацию" onClick={()=>setMenu(v=>!v)}>☰</button>{menu?<div className={styles.mobileMenu} role="dialog" aria-modal="true" aria-label="Навигация"><button onClick={()=>{setMenu(false);trigger.current?.focus()}}>Закрыть</button>{items.map(([l,v])=><button key={v} onClick={()=>{setMenu(false);onNavigate(v)}}>{l}</button>)}</div>:null}</header>
}

function Context({role,scenario}:{role:RoleLabel;scenario:ScenarioId}){const s=scenarioById(scenario);return <div className={styles.context} data-testid="runtime-context-receipt"><span>Роль</span><strong>{role}</strong><span>Сценарий</span><strong>{s.label}</strong><span>Пресет слоёв</span><strong>{s.preset}</strong></div>}

function Map({records=GOLDEN_RECORDS,title="Российская Федерация",compact=false}:{records?:readonly FederalRecord[];title?:string;compact?:boolean}){return <section className={`${styles.map} ${compact?styles.mapCompact:""}`} data-testid="pilot-map" aria-label={`Текстовое представление карты: ${title}`}><div className={styles.mapGrid}/><div className={styles.mapHeading}><span>{title}</span><StatusChip tone="spatial">Карта + список</StatusChip></div>{records.slice(0,8).map((r,i)=><i key={r.id} className={styles.dot} style={{left:`${r.x}%`,top:`${r.y}%`}} aria-hidden>{i<4?i+1:""}</i>)}<div className={styles.mapLegend}><span><i/>Реестровый сигнал</span><span><i/>Кандидат</span><span>Масштаб 1 : 4 200 000</span></div></section>}

function Workspace({role,scenario,mode,query,onRole,onScenario,onMode,onQuery,onRun}:{role:RoleLabel;scenario:ScenarioId;mode:Mode;query:string;onRole:(v:RoleLabel)=>void;onScenario:(v:ScenarioId)=>void;onMode:(v:Mode)=>void;onQuery:(v:string)=>void;onRun:()=>void}){const s=scenarioById(scenario),b=ROLE_BEHAVIOR[role];return <main data-testid="workspace-screen"><Caveat/><div className={styles.workspace}><Map title="РФ · 8 федеральных округов · 41 субъект"/><section className={styles.controls}><div className={styles.eyebrow}>Рабочая область / РФ</div><h1>Федеральное имущество</h1><div className={styles.field}><span>1 Проект</span><strong>PILOT-RF-002 · Федеральное имущество</strong></div><Selector label="2 Роль · 11 ролей" value={role} options={ROLE_OPTIONS.map(v=>({value:v,label:v}))} onChange={onRole} testId="role-switcher"/><p className={styles.disclaimer}>{ROLE_DISCLAIMER}</p><Selector label="3 Сценарий · 8 P0-сценариев" value={s.label} options={SCENARIO_OPTIONS.map(v=>({value:v.id,label:v.label}))} onChange={onScenario} testId="scenario-selector"/><div className={styles.field}><span>4 Территория · РФ → ФО → субъект → город</span><strong>Российская Федерация</strong></div><label>5 Режим поиска</label><SegmentSwitch ariaLabel="Режим поиска" className={styles.segment} options={[{value:"criteria",label:"По критериям"},{value:"map",label:"На карте"}]} value={mode} onChange={onMode}/><div className={styles.field}><span>6 Источники и слои · пресет сценария</span><strong data-testid="layer-preset">{s.preset}</strong></div><label className={styles.query}><span>7 Структурированные критерии · Произвольный запрос</span><textarea value={query} onChange={e=>onQuery(e.target.value)} rows={3}/><small>Неподдерживаемые условия: нет · Все условия · Изменить условия</small></label><p className={styles.conflict}><strong>Конфликт: да</strong> · {s.controls}</p><Button className={styles.wide} onClick={onRun}>8&nbsp; Найти объекты</Button><details className={styles.manifest}><summary>Как роль и сценарий изменяют представление</summary><p><b>KPI:</b> {b.kpi.join(" → ")}</p><p><b>Очередь:</b> {b.queue}</p><p><b>Рекомендация:</b> {b.recommendation}</p><p><b>Действия:</b> {b.actions.join(" · ")}</p><p><b>Результат сценария:</b> {s.output}</p><p><b>Оговорка сценария:</b> {s.caveat}</p><p><b>Следующий шаг:</b> {s.nextAction}</p></details></section></div><span className={styles.fixture} data-testid="fixture-contract">{FEDERAL_RECORDS.length}/{MOSCOW_RECORDS.length}/{FEDERAL_DISTRICT_COUNT}/{SUBJECT_COUNT}</span></main>}

function QueryReceipt(){return <div className={styles.queryReceipt} data-testid="interpreted-query"><b>Интерпретированный запрос</b><span>Москва · федеральные объекты · предварительное вовлечение</span><span><strong>Конфликт: да</strong> · Неподдерживаемые условия: нет</span><button type="button">Все условия</button><button type="button">Изменить условия</button></div>}
function Card({r,index,selected,disabled,toggle,open}:{r:FederalRecord;index:number;selected:boolean;disabled:boolean;toggle:()=>void;open:()=>void}){return <article className={`${styles.card} ${selected?styles.selected:""}`} data-record-id={r.id}><span>{String(index+1).padStart(2,"0")}</span><div><button className={styles.link} onClick={open}>{r.id}</button><small>{r.registry.toLowerCase()} · NSPD · публичный контекст</small><small>Свежесть: {r.freshness}</small></div><button aria-label={`${selected?"Снять выбор":"Выбрать"} ${r.id}`} disabled={disabled&&!selected} onClick={toggle}>{selected?"✓":"+"}</button></article>}
function Results({role,scenario,selected,toggle,open,compare}:{role:RoleLabel;scenario:ScenarioId;selected:string[];toggle:(id:string)=>void;open:(id:string)=>void;compare:()=>void}){const [mode,setMode]=useState<"map"|"list">("map");return <main data-testid="results-screen"><Caveat/><Context role={role} scenario={scenario}/><div className={styles.results}><section><div className={styles.resultsHead}><div><span className={styles.eyebrow}>Результаты / Москва</span><h1>320 кандидатов</h1></div><SegmentSwitch ariaLabel="Представление результатов" options={[{value:"map",label:"Карта"},{value:"list",label:"Список"}]} value={mode} onChange={setMode}/></div><QueryReceipt/>{mode==="map"?<Map records={GOLDEN_RECORDS} title="Москва · map-first выборка"/>:null}</section><aside className={styles.shortlist}><div><b>Краткий список</b><span>{selected.length} из 4 выбрано</span></div>{GOLDEN_RECORDS.map((r,i)=><Card key={r.id} r={r} index={i} selected={selected.includes(r.id)} disabled={selected.length>=4} toggle={()=>toggle(r.id)} open={()=>open(r.id)}/>)}<Button className={styles.wide} disabled={selected.length<2} onClick={compare}>Сравнить {selected.length} объекта</Button></aside></div></main>}

const axes=["Реестр","Использование","Состояние","Доступность","Ограничения","Спрос","Свежесть","Рекомендация"];
function Comparison({records,onOpen,onBack}:{records:FederalRecord[];onOpen:(id:string)=>void;onBack:()=>void}){const [tab,setTab]=useState(0);const r=records[tab]??records[0];return <main className={styles.decision} data-testid="comparison-screen"><Caveat/><header className={styles.screenHead}><div><span className={styles.eyebrow}>Сравнение / Москва</span><h1>Сравнение кандидатов</h1></div><Button variant="secondary" onClick={onBack}>К результатам</Button></header><div className={styles.mobileTabs} role="tablist">{records.map((x,i)=><button key={x.id} role="tab" aria-selected={i===tab} onClick={()=>setTab(i)}>{i+1}</button>)}</div><div className={styles.compareGrid}>{records.map((x,i)=><article key={x.id} data-testid="comparison-card" className={`${styles.compareCard} ${i===tab?styles.mobileActive:""}`}><span>0{i+1}</span><h2>{x.id}</h2><StatusChip tone={x.conflict?"critical":"validation"}>{x.confidence}</StatusChip>{axes.map(a=><div key={a}><b>{a}</b><span>{a==="Реестр"?x.registry:a==="Использование"?x.use:a==="Состояние"?x.condition:a==="Доступность"?(x.accessMinutes?`${x.accessMinutes} мин`:"Данных нет"):a==="Ограничения"?`${x.restrictions} сигнала`:a==="Спрос"?x.demand:a==="Свежесть"?x.freshness:x.recommendation}</span></div>)}<Button variant="secondary" onClick={()=>onOpen(x.id)}>Открыть объект</Button></article>)}</div><section className={styles.decisionSummary}><h2>Основания решения</h2><p><b>Когорта:</b> 320 объектов Москвы · выбрано {records.length}</p><p><b>Рекомендация:</b> сохранить как условных кандидатов; подтвердить источники и блокеры.</p><p><b>Альтернатива:</b> отложить до устранения конфликтов реестра.</p><p><b>Следующий проверяемый шаг:</b> подготовить карточку способа вовлечения.</p><p><b>Конфликт: да · Неподдерживаемые условия: нет</b></p><p>{SCREENING_CAVEAT}</p></section></main>}

function ObjectScreen({r,role,scenario,onEvidence,onSave,onReport,onPermission}:{r:FederalRecord;role:RoleLabel;scenario:ScenarioId;onEvidence:()=>void;onSave:()=>void;onReport:()=>void;onPermission:()=>void}){return <main data-testid="object-dashboard"><Caveat/><Context role={role} scenario={scenario}/><div className={styles.object}><aside className={styles.sources}><h2>Происхождение источников</h2>{SOURCE_RECEIPTS.map(s=><button key={s.id} onClick={onEvidence}><b>{s.name}</b><span>{s.status}</span></button>)}</aside><section><span className={styles.eyebrow}>Карточка объекта / Москва</span><h1>{r.id}</h1><p className={styles.objectCaveat}>{SCREENING_CAVEAT}</p><div className={styles.metrics}><article><span>Реестр</span><b>{r.registry}</b><small>NSPD · 31.07.2026</small></article><article><span>Использование</span><b>{r.use}</b><small>Демонстрационный сигнал</small></article><article><span>Состояние</span><b>{r.condition}</b><small>Требуется проверка</small></article><article><span>Доступность</span><b>{r.accessMinutes?`${r.accessMinutes} мин`:"Данных нет"}</b><small>Контекст маршрута</small></article></div><details open><summary>Ограничения и блокеры</summary><p>Конфликт: да · Неподдерживаемые условия: нет · {r.restrictions} непроверенных сигнала.</p></details><details open><summary>Условная рекомендация</summary><p>{r.recommendation}. Не является юридическим или управленческим заключением.</p></details><details open><summary>Ответственный и следующий шаг</summary><p>Ответственный: Руководитель портфеля · подготовить карточку способа вовлечения.</p></details><div className={styles.actions}><Button onClick={onSave}>Добавить в проект</Button><Button variant="secondary" onClick={onEvidence}>Сведения об источниках</Button><Button variant="secondary" onClick={onReport}>Открыть отчёт</Button><Button variant="quiet" onClick={onPermission}>Открыть границу доступа</Button></div></section></div></main>}

function Evidence({onClose}:{onClose:()=>void}){return <main className={styles.evidence} data-testid="evidence-screen"><header className={styles.screenHead}><div><span className={styles.eyebrow}>Доказательства / источники</span><h1>Сведения об источниках</h1></div><Button variant="secondary" onClick={onClose}>Закрыть сведения</Button></header><aside className={styles.unknown}><b>Правило неизвестных значений</b><p>Нет данных ≠ ноль. {SCREENING_CAVEAT}</p></aside><div className={styles.receipts}>{SOURCE_RECEIPTS.map(s=><article key={s.id} data-source-id={s.id}><div><h2>{s.name}</h2><StatusChip tone={s.tone as StatusChipTone}>{s.status}</StatusChip></div><dl><dt>Класс источника</dt><dd>{s.sourceClass}</dd><dt>Дата</dt><dd>{s.date}</dd><dt>Граница доступа</dt><dd>{s.access}</dd><dt>Свежесть</dt><dd>{s.freshness}</dd><dt>Метод</dt><dd>{s.method}</dd><dt>Вход</dt><dd>{s.input}</dd><dt>Вывод</dt><dd>{s.derivation}</dd><dt>Лицензия</dt><dd>{s.license}</dd><dt>Оговорка</dt><dd>{s.caveat}</dd></dl></article>)}</div></main>}

function Projects({project,role,scenario,onOpen,onNew,onReset}:{project:SavedProject|null;role:RoleLabel;scenario:ScenarioId;onOpen:()=>void;onNew:()=>void;onReset:()=>void}){const p=project??{title:"Предварительное вовлечение · Москва",role,scenario,selectedIds:DEFAULT_SELECTED,activeRecordId:GOLDEN_RECORDS[0].id,query:DEFAULT_QUERY,savedAt:"Не сохранено"};return <main className={styles.projects} data-testid="projects-screen"><header className={styles.screenHead}><div><span className={styles.eyebrow}>Проекты / браузерное сохранение</span><h1>Сохранённое состояние</h1></div><Button onClick={onNew}>Новый поиск</Button></header><aside className={styles.local}>Состояние хранится только в этом браузере. Официальная интеграция не используется.</aside><article className={styles.projectCard}><div><h2>{p.title}</h2><StatusChip tone={project?"spatial":"neutral"}>{project?"Сохранено":"Демонстрация"}</StatusChip></div><div className={styles.projectMetrics}><span><b>{p.selectedIds.length}</b> объекта</span><span><b>320</b> Москва</span><span><b>8</b> ФО</span><span><b>41</b> субъект</span></div><div className={styles.saved} data-testid="saved-state-receipt"><p><b>Роль:</b> {p.role}</p><p><b>Сценарий:</b> {scenarioById(p.scenario).label}</p><p><b>Пресет:</b> {scenarioById(p.scenario).preset}</p><p><b>Объект:</b> {p.activeRecordId}</p><p><b>Сохранено:</b> {p.savedAt}</p><p><b>Конфликт: да · Неподдерживаемые условия: нет</b></p><p>{SCREENING_CAVEAT}</p></div><div className={styles.actions}><Button onClick={onOpen}>Открыть проект</Button><Button variant="quiet" onClick={onReset}>Очистить сохранение</Button></div></article></main>}

function Report({r,role,scenario,onBack}:{r:FederalRecord;role:RoleLabel;scenario:ScenarioId;onBack:()=>void}){const b=ROLE_BEHAVIOR[role];return <main className={styles.report} data-testid="printable-report"><div className={styles.printActions}><Button variant="secondary" onClick={onBack}>Назад</Button><Button onClick={()=>window.print()}>Печать</Button></div><header><div><span className={styles.eyebrow}>Печатная записка · PILOT-RF-002</span><h1>Предварительное вовлечение федерального объекта</h1></div><IdentitySymbol/></header><Context role={role} scenario={scenario}/><section><h2>Исходный вопрос</h2><p>{DEFAULT_QUERY}</p></section><section><h2>Когорта и выбор</h2><p>Российская Федерация · Москва · 320 кандидатов · выбран {r.id}.</p></section><div className={styles.reportGrid}><section><h2>Рекомендация</h2><p>{r.recommendation}.</p></section><section><h2>Альтернативы и блокеры</h2><p>Отложить до подтверждения. Конфликт: да · Неподдерживаемые условия: нет.</p></section><section><h2>Достоверность</h2><p>{r.confidence}; неизвестные значения не заменены.</p></section><section><h2>Ответственный</h2><p>Руководитель портфеля.</p></section></div><Map records={[r]} title="Москва · контекст объекта" compact/><section><h2>Происхождение источников</h2><p>{SOURCE_RECEIPTS.map(s=>`${s.name}: ${s.status}`).join(" · ")}</p></section><section><h2>Следующий проверяемый шаг</h2><p>{scenarioById(scenario).nextAction}. Порядок разделов роли: {b.report.join(" → ")}.</p></section><footer>{SCREENING_CAVEAT}</footer></main>}

const stateCopy:Record<RuntimeState,{title:string;text:string;action:string}>={loading:{title:"Формируем предварительную выборку",text:"Сопоставляем демонстрационные записи, источники и условия запроса.",action:"Отмена"},empty:{title:"По условиям объекты не найдены",text:"Снимите один из фильтров или измените территорию. Неизвестные значения не считаются нулём.",action:"Изменить условия"},"map-error":{title:"Карта временно недоступна",text:"Список результатов остаётся доступным; карта не блокирует принятие следующего шага.",action:"Открыть список"},"source-unavailable":{title:"Источник недоступен",text:"Значения не подменяются. Сохраните запрос и повторите проверку после восстановления источника.",action:"Продолжить без источника"},"permission-required":{title:"Требуется разрешение",text:"Источник находится за отдельной границей доступа. Действие недоступно без разрешения.",action:"Назад"}};
function StateScreen({state,onAction}:{state:RuntimeState;onAction:()=>void}){const c=stateCopy[state];return <main className={styles.state} data-testid={`state-${state}`}><Caveat/><section><span className={styles.eyebrow}>Системное состояние</span><h1>{c.title}</h1><p>{c.text}</p>{state==="loading"?<div className={styles.skeleton}><i/><i/><i/></div>:null}{state==="map-error"?<div className={styles.fallbackList}><b>Доступные результаты</b><span>ДЕМО-RF-MOW-031 · реестровый конфликт</span><span>ДЕМО-RF-MOW-114 · неполные сведения</span></div>:null}<aside><b>Конфликт: да · Неподдерживаемые условия: нет</b><p>Следующий проверяемый шаг: {state==="permission-required"?"получить разрешение или использовать доступный источник":"проверить условия и происхождение данных"}.</p><p>{SCREENING_CAVEAT}</p></aside><Button onClick={onAction}>{c.action}</Button></section></main>}

function readProject():SavedProject|null{try{const v=localStorage.getItem(PROJECT_KEY);return v?JSON.parse(v) as SavedProject:null}catch{return null}}
export function ImplementationBaselineShell(){const [view,setView]=useState<View>("workspace"),[runtime,setRuntime]=useState<RuntimeState|null>(null),[role,setRole]=useState<RoleLabel>(DEFAULT_ROLE),[scenario,setScenario]=useState<ScenarioId>(DEFAULT_SCENARIO),[mode,setMode]=useState<Mode>("criteria"),[query,setQuery]=useState(DEFAULT_QUERY),[selected,setSelected]=useState<string[]>(DEFAULT_SELECTED),[active,setActive]=useState(DEFAULT_SELECTED[0]),[project,setProject]=useState<SavedProject|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const sync=useCallback((v:View,state:RuntimeState|null=null,id?:string,replace=false)=>{const u=new URL(location.href);u.searchParams.set("view",v);u.searchParams.set("role",role);u.searchParams.set("scenario",scenario);state?u.searchParams.set("state",state):u.searchParams.delete("state");id?u.searchParams.set("object",id):!["object","evidence","report"].includes(v)&&u.searchParams.delete("object");history[replace?"replaceState":"pushState"](null,"",u.pathname+u.search)},[role,scenario]);
  const nav=useCallback((v:View,id?:string)=>{setView(v);setRuntime(null);if(id)setActive(id);sync(v,null,id);scrollTo({top:0,behavior:"instant"})},[sync]);
  useEffect(()=>{const read=()=>{const p=new URLSearchParams(location.search),v=viewFrom(p.get("view"));const rr=p.get("role"),ss=p.get("scenario");if(ROLE_OPTIONS.includes(rr as RoleLabel))setRole(rr as RoleLabel);if(SCENARIO_OPTIONS.some(s=>s.id===ss))setScenario(ss as ScenarioId);setView(v);setRuntime(v==="state"?stateFrom(p.get("state")):null);const id=p.get("object");if(id)setActive(getFederalRecord(id).id);if(v==="comparison"&&p.get("compare")==="4")setSelected(GOLDEN_RECORDS.map(r=>r.id))};read();setProject(readProject());addEventListener("popstate",read);return()=>removeEventListener("popstate",read)},[]);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
  const activeRecord=useMemo(()=>getFederalRecord(active),[active]);
  const run=()=>{setView("state");setRuntime("loading");sync("state","loading");timer.current=setTimeout(()=>{setView("results");setRuntime(null);sync("results",null,undefined,true)},420)};
  const save=()=>{const p:SavedProject={title:"Предварительное вовлечение · Москва",role,scenario,selectedIds:selected,activeRecordId:active,query,savedAt:new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date())};localStorage.setItem(PROJECT_KEY,JSON.stringify(p));setProject(p);nav("projects")};
  const restore=()=>{if(project){setRole(project.role);setScenario(project.scenario);setSelected(project.selectedIds);setActive(project.activeRecordId);setQuery(project.query)}nav("results")};
  const showState=(s:RuntimeState)=>{setView("state");setRuntime(s);sync("state",s)};
  return <div className={styles.root} lang="ru" data-testid="rosim-pilot-root"><TopNav view={view} onNavigate={nav}/>{view==="workspace"?<Workspace role={role} scenario={scenario} mode={mode} query={query} onRole={r=>{setRole(r);setScenario(ROLE_BEHAVIOR[r].defaultScenario)}} onScenario={setScenario} onMode={setMode} onQuery={setQuery} onRun={run}/>:null}{view==="results"?<Results role={role} scenario={scenario} selected={selected} toggle={id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):v.length<4?[...v,id]:v)} open={id=>nav("object",id)} compare={()=>nav("comparison")}/>:null}{view==="comparison"?<Comparison records={selected.map(getFederalRecord)} onOpen={id=>nav("object",id)} onBack={()=>nav("results")}/>:null}{view==="object"?<ObjectScreen r={activeRecord} role={role} scenario={scenario} onEvidence={()=>nav("evidence",active)} onSave={save} onReport={()=>nav("report",active)} onPermission={()=>showState("permission-required")}/>:null}{view==="evidence"?<Evidence onClose={()=>nav("object",active)}/>:null}{view==="projects"?<Projects project={project} role={role} scenario={scenario} onOpen={restore} onNew={()=>nav("workspace")} onReset={()=>{localStorage.removeItem(PROJECT_KEY);setProject(null)}}/>:null}{view==="report"?<Report r={activeRecord} role={role} scenario={scenario} onBack={()=>nav("object",active)}/>:null}{view==="state"&&runtime?<StateScreen state={runtime} onAction={()=>runtime==="map-error"?nav("results"):nav("workspace")}/>:null}</div>}
