insert into public.source_registry_snapshots
(source_id, source_name, category, access_mode, connection_status, source_mode, data_quality_tier, record_count, quality, lineage, caveat)
values
('dld-dubai-pulse-public','DLD / Dubai Pulse public real estate snapshots','real-estate','manual-snapshot','manual_import_ready','snapshot_metadata','requires-validation',0,'{"confidence":"requires-validation","officialClaimAllowed":false,"statusNote":"Manual CSV snapshot path prepared; no live API connected."}'::jsonb,'{"provider":"Dubai Land Department / Dubai Pulse","allowedUse":["market activity proxy","rental demand proxy","development context","source lineage"]}'::jsonb,'Screening hypothesis; official validation required; not a legal, cadastral, zoning, planning or valuation conclusion.'),
('osm-geofabrik-baseline','OpenStreetMap / Geofabrik open geospatial baseline','transport-poi-buildings','open-snapshot','manual_import_ready','open_geospatial_snapshot_metadata','open-context',0,'{"confidence":"medium-after-snapshot","officialClaimAllowed":false,"statusNote":"Open snapshot path prepared; not official municipal GIS."}'::jsonb,'{"provider":"OpenStreetMap contributors / Geofabrik","allowedUse":["accessibility proxy","road proximity context","POI and amenity context","building-density proxy"]}'::jsonb,'Screening hypothesis; official validation required; not a legal, cadastral, zoning, planning or valuation conclusion.'),
('overture-maps-open','Overture Maps buildings / places / transportation snapshots','buildings-places-transport','public-download','manual_import_ready','open_snapshot_metadata','open-context',0,'{"confidence":"medium-after-snapshot","officialClaimAllowed":false,"statusNote":"Public download / GeoJSON path prepared; not official Dubai GIS."}'::jsonb,'{"provider":"Overture Maps Foundation","allowedUse":["open building context","places and demand-anchor context","transport network context"]}'::jsonb,'Screening hypothesis; official validation required; not a legal, cadastral, zoning, planning or valuation conclusion.'),
('open-meteo-nasa-power-climate','Open-Meteo and NASA POWER climate / energy context','climate-energy','open-api','connected_context_ready','api_context_metadata','screening',0,'{"confidence":"screening","officialClaimAllowed":false,"statusNote":"Open API context path prepared for AOI centroid queries."}'::jsonb,'{"providers":["Open-Meteo","NASA POWER"],"allowedUse":["heat and rainfall screening proxy","solar radiation and wind context"]}'::jsonb,'Screening hypothesis; official validation required; not a legal, cadastral, zoning, planning or valuation conclusion.'),
('copernicus-sentinel-metadata','Copernicus / Sentinel metadata availability','satellite-metadata','token-optional','token_required','metadata_query_planned','requires-validation',0,'{"confidence":"requires-validation","officialClaimAllowed":false,"statusNote":"Metadata availability path registered; no imagery download or raster analytics connected."}'::jsonb,'{"provider":"Copernicus Data Space / Sentinel","allowedUse":["satellite availability planning","future remote-sensing lineage"]}'::jsonb,'Screening hypothesis; official validation required; not a legal, cadastral, zoning, planning or valuation conclusion.');

insert into public.external_data_snapshots
(source_id, category, source_mode, raw_file_name, normalized_path, record_count, quality, manifest)
values
('dld-dubai-pulse-public','real-estate','manual_snapshot_metadata',null,'data/normalized/dld_market_summary.json',0,'{"status":"manual_import_ready","noLiveApi":true}'::jsonb,'{"stage":"registry_seed","sourceGroup":1}'::jsonb),
('osm-geofabrik-baseline','transport-poi-buildings','open_snapshot_metadata',null,'data/normalized/osm_source_quality.json',0,'{"status":"manual_import_ready","notOfficialGIS":true}'::jsonb,'{"stage":"registry_seed","sourceGroup":2}'::jsonb),
('overture-maps-open','buildings-places-transport','open_snapshot_metadata',null,'data/normalized/overture_source_quality.json',0,'{"status":"manual_import_ready","notOfficialGIS":true}'::jsonb,'{"stage":"registry_seed","sourceGroup":3}'::jsonb),
('open-meteo-nasa-power-climate','climate-energy','api_context_metadata',null,'api-context/open-meteo-nasa-power',0,'{"status":"connected_context_ready","screeningOnly":true}'::jsonb,'{"stage":"registry_seed","sourceGroup":4}'::jsonb),
('copernicus-sentinel-metadata','satellite-metadata','metadata_query_planned',null,'api-context/copernicus-sentinel-metadata',0,'{"status":"token_required","noImageryDownload":true}'::jsonb,'{"stage":"registry_seed","sourceGroup":5}'::jsonb);
